#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}}
REPO=${REPO:-rancher}

if [ ! -e ../bin/dhcp ]; then
    ../scripts/build
fi

cp ../bin/* .
docker build -t ${REPO}/vm-net:${TAG} .

echo Built ${REPO}/vm-net:${TAG}
